{% set name = "pygasflow" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygasflow-{{ version }}.tar.gz
  sha256: 5c606f96e607b0533a25c09482ccc279df01e886dd73e7ee20d3a1de25498b1d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - matplotlib-base
    - pandas
    - param
    - panel
    - colorcet

test:
  imports:
    - pygasflow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Davide-sd/pygasflow
  summary: Ideal Gasdynamics utilities for Python 3.6+
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Davide-sd
